### ISSUE TITLE
你好，部署的最后一步pm2没有发现index.js。

### ISSUE THREAD

**Issue by fattypiggy** [heartsuit/devcloud-vue#1]
![image](https://user-images.githubusercontent.com/17648041/121528478-16842f00-ca2e-11eb-8cf3-17d1fc74d5c7.png)
![image](https://user-images.githubusercontent.com/17648041/121528531-23a11e00-ca2e-11eb-997b-c2f13415df77.png)

**Comment by fattypiggy** [comment]
我是用我自己的程序，照着您的方法做的，出现了以上的问题。

**Comment by heartsuit** [comment]
这个index.js属于一个Node.js编写的后端服务，实现了静态资源托管功能，参考：https://heartsuit.blog.csdn.net/article/details/89420934

**Comment by heartsuit** [comment]
> 
> 
> 我是用我自己的程序，照着您的方法做的，出现了以上的问题。

这个index.js属于一个Node.js编写的后端服务，实现了静态资源托管功能，参考：https://heartsuit.blog.csdn.net/article/details/89420934

**Comment by fattypiggy** [comment]
> > 我是用我自己的程序，照着您的方法做的，出现了以上的问题。
> 
> 这个index.js属于一个Node.js编写的后端服务，实现了静态资源托管功能，参考：https://heartsuit.blog.csdn.net/article/details/89420934

谢谢
